"""Integration dispatch — maps module names to integration run() functions."""

from audit_code.integrations import (
    bandit,
    checkstyle,
    clang_tidy,
    clippy,
    cppcheck,
    credo,
    dart_analyze,
    detekt,
    dotnet_format,
    eslint,
    go_vet,
    golangci_lint,
    hlint,
    htmlhint,
    luacheck,
    phpstan,
    pmd,
    prettier,
    rubocop,
    rustfmt,
    scalafix,
    semgrep,
    stylelint,
    swiftlint,
    zig_fmt,
)

INTEGRATIONS = {
    "bandit": bandit,
    "checkstyle": checkstyle,
    "clang-tidy": clang_tidy,
    "clippy": clippy,
    "cppcheck": cppcheck,
    "credo": credo,
    "dart-analyze": dart_analyze,
    "detekt": detekt,
    "dotnet-format": dotnet_format,
    "eslint": eslint,
    "go-vet": go_vet,
    "golangci-lint": golangci_lint,
    "hlint": hlint,
    "htmlhint": htmlhint,
    "luacheck": luacheck,
    "phpstan": phpstan,
    "pmd": pmd,
    "prettier": prettier,
    "rubocop": rubocop,
    "rustfmt": rustfmt,
    "scalafix": scalafix,
    "semgrep": semgrep,
    "stylelint": stylelint,
    "swiftlint": swiftlint,
    "zig-fmt": zig_fmt,
}
